name: Finite
options:
  bundleIdPrefix: com.finite
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_KEY_UILaunchScreen_Generation: true
    INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

targets:
  Finite:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Finite
        excludes:
          - "**/*.xcassets"
      - path: Finite/Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.finite.app
        CODE_SIGN_ENTITLEMENTS: Finite/Finite.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: Finite/Info.plist
    dependencies:
      - package: Supabase
      - target: FiniteWidgetExtension
        embed: true
    entitlements:
      path: Finite/Finite.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
        com.apple.security.application-groups:
          - group.com.finite.app

  FiniteWidgetExtension:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: FiniteWidget
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.finite.app.widget
        CODE_SIGN_ENTITLEMENTS: FiniteWidget/FiniteWidget.entitlements
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: FiniteWidget/Info.plist
    entitlements:
      path: FiniteWidget/FiniteWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.finite.app

schemes:
  Finite:
    build:
      targets:
        Finite: all
        FiniteWidgetExtension: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
